@startuml
skinparam classAttributeIconSize 0

class OrderedCollection {
        - array
        - firstIndex
        - lastIndex

        + add(newObject)
        + addBeforeIndex(newObject, index)
}

@enduml
